ingress:
  enabled: true
  hosts:
    - grafana.nginx-example.com
persistence:
  enabled: false
# Example for datasources file https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
datasources:
  datasources.yaml: # Must be name like this!
    apiVersion: 1
    datasources:
      - name: Prometheus
        # One of https://grafana.com/docs/grafana/latest/datasources/#supported-data-sources
        type: prometheus
        # proxy or direct (Server or Browser in the UI)
        access: proxy
        url: http://prometheus-server.prometheus
        editable: true
        isDefault: true
sidecar:
  dashboards:
    enabled: true
    label: grafana-dashboard
    provider:
      allowUiUpdates: true
dashboards:
  prometheus:
    stats:
      # Ref: https://grafana.com/dashboards/2
      gnetId: 2
      revision: 2
      datasource: Prometheus
  k8s:
    cluster:
      gnetId: 3149
      revision: 1
      datasource: Prometheus

# Example for dashboards https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
dashboardProviders:
  dashboardproviders.yaml: # Must be name like this!
    apiVersion: 1
    providers:
    - name: prometheus-external
      folder: Prometheus
      type: file
      disableDeletion: false
      # updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        # Helm mounts files from the dashboardsConfigMaps here
        path: /var/lib/grafana/dashboards/prometheus
    - name: k8s-external
      folder: K8S
      type: file
      disableDeletion: false
      # updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        # Helm mounts files from the dashboardsConfigMaps here
        path: /var/lib/grafana/dashboards/k8s

# With the following option can mount a ConfigMap as dashboard but it doesn't monitor changes (I think)
# dashboardsConfigMaps:
#   nginx: grafana-dashboard-nginx