kind: Namespace
apiVersion: v1
metadata:
  name: nginx

---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: nginx
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    # This is the pod template of 1 container
    spec:
      containers:
        - name: app
          image: cristianriano/nginxdemo
          ports:
            - containerPort: 80
        - name: prometheus-exporter
          # https://github.com/nginxinc/nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:0.8.0
          # Can be configiured either with flags or ENV variables
          args:
            - -nginx.scrape-uri=http://localhost:80/nginx_status
          # env:
          #   - name: SCRAPE_URI
          #     value: "http://localhost:80/nginx_status"
          ports:
            - name: metrics
              containerPort: 9113

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx
spec:
  # https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  selector:
    app: nginx-app
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80