kind: Namespace
apiVersion: v1
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx

---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: nginx
  name: nginx-deployment
  labels:
    app.kubernetes.io/name: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    # This is the pod template of 1 container
    spec:
      containers:
        - name: app
          image: cristianriano/nginxdemo
          ports:
            - containerPort: 80
        - name: prometheus-exporter
          # https://github.com/nginxinc/nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:0.8.0
          # Can be configiured either with flags or ENV variables
          args:
            - -nginx.scrape-uri=http://localhost:80/nginx_status
          # env:
          #   - name: SCRAPE_URI
          #     value: "http://localhost:80/nginx_status"
          ports:
            - name: exporter
              containerPort: 9113

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx
spec:
  # https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  rules:
  # Add more entries to the array for different domains or subdomains (one for each)
  - host: nginx-example.com
    http:
      paths:
      - path: '/'
        pathType: Prefix # or Exact
        backend:
          service:
            name: nginx-service
            port:
              # Either number or number
              name: nginx
              # number: 80
