#!/bin/bash

minikube start --driver=hyperkit --cpus 4 --memory 8192
minikube addons enable ingress

sleep 20
kubectl apply -f resources/11-nginx-hello.yml \
              -f resources/11-nginx-ingress.yml \
              -f resources/12-prometheus-config.yml \
              -f resources/13-grafana-config.yml \
              -f resources/14-grafana-dashboards.yml \

sleep 2
helm install prometheus prometheus-community/prometheus --values prometheus-values.yml -n prometheus

sleep 2
helm install grafana grafana/grafana --values grafana-values.yml -n grafana

kubectl get ingress -n nginx
