apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pdfdocuments.k8s.example.com
spec:
  # K8S api will serve the resource like /apis/<group>/<version>/namespaces/<namespace>/<plural-resource>
  # K8S can list all resources with `kubectl api-resources`
  group: k8s.example.com
  # It can be namespaced or cluster-scoped
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # The schema of the CDR
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
  names:
    kind: PdfDocument
    # This can be used with `kubectl get pdfdocument(s)`
    singular: pdfdocument
    plural: pdfdocuments
    shortNames:
      - pdf
      - pdfs